package apply

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLuaPreviewRestoresTheWholeConfiguration(t *testing.T) {
	for _, failApply := range []bool{false, true} {
		t.Run(map[bool]string{false: "timeout", true: "apply failure"}[failApply], func(t *testing.T) {
			reply := "ok"
			if failApply {
				reply = "error: probe missing"
			}
			engine, target, _ := initLuaProbeTestEngine(t, reply, nil)
			root := filepath.Join(filepath.Dir(target), "hyprland.lua")
			original, err := os.ReadFile(root)
			if err != nil {
				t.Fatal(err)
			}
			state, err := engine.Apply(context.Background(), newTestProfile(), monitors, ApplyModeInteractive)
			if failApply {
				if err == nil {
					t.Fatal("expected the apply to fail")
				}
			} else {
				if err != nil {
					t.Fatal(err)
				}
				if err := engine.Revert(context.Background(), state); err != nil {
					t.Fatal(err)
				}
				if err := engine.Revert(context.Background(), state); err != nil {
					t.Fatalf("rollback retry: %v", err)
				}
			}
			if got, err := os.ReadFile(root); err != nil || string(got) != string(original) {
				t.Fatalf("root config was not restored: %s (%v)", got, err)
			}
			if _, err := os.Stat(target); !os.IsNotExist(err) {
				t.Fatalf("new target survived rollback: %v", err)
			}
		})
	}
}

func TestRollbackDoesNotOverwriteAnEditMadeDuringPreview(t *testing.T) {
	engine, target, _ := initLuaProbeTestEngine(t, "ok", nil)
	state, err := engine.Apply(context.Background(), newTestProfile(), monitors, ApplyModeInteractive)
	if err != nil {
		t.Fatal(err)
	}
	root := filepath.Join(filepath.Dir(target), "hyprland.lua")
	changed := append(append([]byte(nil), state.RootWritten...), []byte("-- a concurrent user edit\n")...)
	if err := os.WriteFile(root, changed, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := engine.Revert(context.Background(), state); err == nil || !strings.Contains(err.Error(), "changed during") {
		t.Fatalf("expected an actionable conflict, got %v", err)
	}
	if got, err := os.ReadFile(root); err != nil || string(got) != string(changed) {
		t.Fatal("overwrote the user edit")
	}
	if _, err := os.Stat(target); err != nil {
		t.Fatal("left the edited include pointing at a missing file")
	}
}

func TestPreviewDoesNotRetireTheLegacySafetyNet(t *testing.T) {
	engine, target, _ := initLuaProbeTestEngine(t, "ok", nil)
	legacy := filepath.Join(filepath.Dir(target), "monitors.lua")
	original := "-- Generated by hyprmoncfg\nhl.monitor({ output = 'eDP-1', scale = 1 })\n"
	if err := os.WriteFile(legacy, []byte(original), 0o644); err != nil {
		t.Fatal(err)
	}
	state, err := engine.Apply(context.Background(), newTestProfile(), monitors, ApplyModeInteractive)
	if err != nil {
		t.Fatal(err)
	}
	if err := engine.Revert(context.Background(), state); err != nil {
		t.Fatal(err)
	}
	if got, err := os.ReadFile(legacy); err != nil || string(got) != original {
		t.Fatalf("preview retired the previous rules: %s (%v)", got, err)
	}
}
