package config

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type FileSnapshot struct {
	Path    string
	Exists  bool
	Content []byte
}

type HyprConfigFormat int

const (
	HyprConfigLegacy HyprConfigFormat = iota
	HyprConfigLua
)

const (
	hyprlandConfigEnv = "HYPRLAND_CONFIG"
	monitorsConfEnv   = "HYPRMONCFG_MONITORS_CONF"
)

const (
	GeneratedLegacyHeader = "# Generated by hyprmoncfg"
	GeneratedLuaHeader    = "-- Generated by hyprmoncfg"
)

type ResolvedHyprConfig struct {
	Format       HyprConfigFormat
	RootPath     string
	MonitorsPath string
}

func GeneratedHeader(format HyprConfigFormat) string {
	if format == HyprConfigLua {
		return GeneratedLuaHeader
	}
	return GeneratedLegacyHeader
}

func IsGeneratedMonitorsConfig(content []byte) bool {
	text := strings.TrimPrefix(string(content), "\ufeff")
	firstLine, _, _ := strings.Cut(text, "\n")
	firstLine = strings.TrimSuffix(firstLine, "\r")
	return firstLine == GeneratedLegacyHeader || firstLine == GeneratedLuaHeader
}

// NeutralizeGeneratedMonitorsConfig removes runtime monitor rules while
// retaining a valid, owned include target. A generated clamshell layout can
// otherwise persist an unconditional internal-panel disable across logout or
// reboot while the external output it enables is absent at the next login.
// User-owned files are never rewritten.
func NeutralizeGeneratedMonitorsConfig(path string) (bool, error) {
	snapshot, err := SnapshotFile(path)
	if err != nil {
		return false, err
	}
	if !snapshot.Exists || !IsGeneratedMonitorsConfig(snapshot.Content) {
		return false, nil
	}

	text := strings.TrimPrefix(string(snapshot.Content), "\ufeff")
	header, _, _ := strings.Cut(text, "\n")
	header = strings.TrimSuffix(header, "\r")
	neutral := []byte(header + "\n")
	if string(snapshot.Content) == string(neutral) {
		return false, nil
	}
	if err := WriteFileAtomic(path, neutral, 0o644); err != nil {
		return false, err
	}
	return true, nil
}

func HyprlandDir() (string, error) {
	if xdg := os.Getenv("XDG_CONFIG_HOME"); xdg != "" {
		return filepath.Join(xdg, "hypr"), nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	if home == "" {
		return "", errors.New("unable to resolve home directory")
	}
	return filepath.Join(home, ".config", "hypr"), nil
}

// HyprlandMonitorsConfPath is where hyprmoncfg used to write, and where many
// distributions ship a monitors config of their own.
func HyprlandMonitorsConfPath() (string, error) {
	dir, err := HyprlandDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "monitors.conf"), nil
}

func HyprlandMonitorsLuaPath() (string, error) {
	dir, err := HyprlandDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "monitors.lua"), nil
}

// HyprlandGeneratedPath is the file hyprmoncfg creates and owns, so it never
// has to overwrite a config someone else wrote.
func HyprlandGeneratedPath(format HyprConfigFormat) (string, error) {
	dir, err := HyprlandDir()
	if err != nil {
		return "", err
	}
	extension := ".conf"
	if format == HyprConfigLua {
		extension = ".lua"
	}
	return filepath.Join(dir, GeneratedMonitorsBasename+extension), nil
}

// LegacyMonitorsPath is the conventional path for a format, which hyprmoncfg
// retires once it owns a file of its own.
func LegacyMonitorsPath(format HyprConfigFormat) (string, error) {
	if format == HyprConfigLua {
		return HyprlandMonitorsLuaPath()
	}
	return HyprlandMonitorsConfPath()
}

func HyprlandMainConfigPath() (string, error) {
	dir, err := HyprlandDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "hyprland.conf"), nil
}

func HyprlandLuaConfigPath() (string, error) {
	dir, err := HyprlandDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "hyprland.lua"), nil
}

func ResolveMonitorsConfPath(explicit string) (string, error) {
	configured := environmentOverride(explicit, monitorsConfEnv)
	if strings.TrimSpace(configured) == "" {
		return HyprlandMonitorsConfPath()
	}
	return resolvePath(configured, "")
}

func ResolveHyprlandConfigPath(explicit string) (string, error) {
	configured := environmentOverride(explicit, hyprlandConfigEnv)
	if strings.TrimSpace(configured) == "" {
		return HyprlandMainConfigPath()
	}
	return resolvePath(configured, "")
}

func ResolveHyprlandConfig(version string, explicitMonitorsPath string, explicitRootPath string) (ResolvedHyprConfig, error) {
	format, rootPath, err := resolveHyprConfigRoot(version, explicitRootPath)
	if err != nil {
		return ResolvedHyprConfig{}, err
	}

	monitorsPath, err := resolveHyprConfigMonitors(format, explicitMonitorsPath)
	if err != nil {
		return ResolvedHyprConfig{}, err
	}

	return ResolvedHyprConfig{
		Format:       format,
		RootPath:     rootPath,
		MonitorsPath: monitorsPath,
	}, nil
}

func resolveHyprConfigRoot(version string, explicit string) (HyprConfigFormat, string, error) {
	configured := environmentOverride(explicit, hyprlandConfigEnv)
	if strings.TrimSpace(configured) != "" {
		rootPath, err := resolvePath(configured, "")
		if err != nil {
			return HyprConfigLegacy, "", err
		}
		switch strings.ToLower(filepath.Ext(rootPath)) {
		case ".lua":
			return HyprConfigLua, rootPath, nil
		case ".conf":
			return HyprConfigLegacy, rootPath, nil
		default:
			return HyprConfigLegacy, "", fmt.Errorf("cannot infer Hyprland config format from %s", rootPath)
		}
	}

	if versionAtLeast(version, 0, 55, 0) {
		luaPath, err := HyprlandLuaConfigPath()
		if err != nil {
			return HyprConfigLegacy, "", err
		}
		if _, err := os.Stat(luaPath); err == nil {
			return HyprConfigLua, luaPath, nil
		} else if err != nil && !errors.Is(err, os.ErrNotExist) {
			return HyprConfigLegacy, "", err
		}
	}

	rootPath, err := HyprlandMainConfigPath()
	return HyprConfigLegacy, rootPath, err
}

func environmentOverride(explicit string, name string) string {
	if strings.TrimSpace(explicit) != "" {
		return explicit
	}
	return os.Getenv(name)
}

func resolveHyprConfigMonitors(format HyprConfigFormat, explicit string) (string, error) {
	configured := environmentOverride(explicit, monitorsConfEnv)
	if strings.TrimSpace(configured) != "" {
		return resolvePath(configured, "")
	}
	return HyprlandGeneratedPath(format)
}

func resolvePath(value string, baseDir string) (string, error) {
	value = strings.TrimSpace(strings.Trim(value, `"'`))
	if value == "" {
		return "", errors.New("path is empty")
	}

	expanded, err := expandHome(value)
	if err != nil {
		return "", err
	}
	expanded = os.ExpandEnv(expanded)
	if !filepath.IsAbs(expanded) {
		if baseDir != "" {
			expanded = filepath.Join(baseDir, expanded)
		} else {
			expanded, err = filepath.Abs(expanded)
			if err != nil {
				return "", err
			}
		}
	}
	return filepath.Clean(expanded), nil
}

func expandHome(value string) (string, error) {
	if value == "~" {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		return home, nil
	}
	if !strings.HasPrefix(value, "~/") {
		return value, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, value[2:]), nil
}

func hasGlob(value string) bool {
	return strings.ContainsAny(value, "*?[")
}

func versionAtLeast(value string, major int, minor int, patch int) bool {
	parts := strings.Split(strings.TrimPrefix(strings.TrimSpace(value), "v"), ".")
	got := []int{0, 0, 0}
	for i := 0; i < len(parts) && i < len(got); i++ {
		part := parts[i]
		for j, r := range part {
			if r < '0' || r > '9' {
				part = part[:j]
				break
			}
		}
		if part == "" {
			continue
		}
		parsed, err := strconv.Atoi(part)
		if err != nil {
			continue
		}
		got[i] = parsed
	}
	want := []int{major, minor, patch}
	for i := range want {
		if got[i] > want[i] {
			return true
		}
		if got[i] < want[i] {
			return false
		}
	}
	return true
}

func SnapshotFile(path string) (FileSnapshot, error) {
	content, err := os.ReadFile(path)
	if err == nil {
		return FileSnapshot{
			Path:    path,
			Exists:  true,
			Content: content,
		}, nil
	}
	if errors.Is(err, os.ErrNotExist) {
		return FileSnapshot{Path: path}, nil
	}
	return FileSnapshot{}, err
}

func (s FileSnapshot) Restore() error {
	if s.Path == "" {
		return nil
	}
	if s.Exists {
		return WriteFileAtomic(s.Path, s.Content, 0o644)
	}
	if err := os.Remove(s.Path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	return nil
}

// ResolveSymlink follows a path to the file it really names, so callers edit a
// dotfile manager's source file instead of replacing the link that points at
// it. A path that is not a link, or that cannot be resolved, comes back as it
// went in.
func ResolveSymlink(path string) string {
	resolved, err := filepath.EvalSymlinks(path)
	if err != nil || strings.TrimSpace(resolved) == "" {
		return path
	}
	return resolved
}

// Writable reports whether hyprmoncfg can edit a config file in place, after
// following any symlink. A read-only target, such as one in the Nix store, is
// somebody else's to change: hyprmoncfg has to tell the user what to add rather
// than fail on every apply.
func Writable(path string) bool {
	path = ResolveSymlink(path)
	info, err := os.Stat(path)
	if err != nil {
		return os.IsNotExist(err) && dirWritable(filepath.Dir(path))
	}
	// Treat an explicitly read-only file as belonging to its generator even
	// when the current process is root and could bypass the mode bits. Besides
	// keeping root-run builds honest, this prevents a privileged invocation
	// from rewriting immutable-style configuration such as a Nix store target.
	if info.Mode().Perm()&0o222 == 0 {
		return false
	}

	file, err := os.OpenFile(path, os.O_WRONLY, 0)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

func dirWritable(dir string) bool {
	probe, err := os.CreateTemp(dir, ".hyprmoncfg-probe-*")
	if err != nil {
		return false
	}
	name := probe.Name()
	_ = probe.Close()
	_ = os.Remove(name)
	return true
}

func WriteFileAtomic(path string, content []byte, perm os.FileMode) error {
	// Write through a symlink rather than over it. Dotfile managers point
	// ~/.config/hypr at a file they own, and renaming onto the link would
	// silently replace their link with a plain file of ours.
	path = ResolveSymlink(path)

	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(filepath.Dir(path), ".hyprmoncfg-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.Write(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
