package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestIsGeneratedMonitorsConfig(t *testing.T) {
	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{name: "legacy", content: GeneratedLegacyHeader + "\nmonitor = DP-1", want: true},
		{name: "lua", content: GeneratedLuaHeader + "\nhl.monitor({})", want: true},
		{name: "crlf", content: GeneratedLegacyHeader + "\r\nmonitor = DP-1", want: true},
		{name: "byte order mark", content: "\ufeff" + GeneratedLuaHeader + "\n", want: true},
		{name: "marker after user content", content: "-- user config\n" + GeneratedLuaHeader + "\n", want: false},
		{name: "other generator", content: "# Generated by another tool\n", want: false},
		{name: "empty", content: "", want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := IsGeneratedMonitorsConfig([]byte(tt.content)); got != tt.want {
				t.Fatalf("IsGeneratedMonitorsConfig() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestNeutralizeGeneratedMonitorsConfig(t *testing.T) {
	tests := []struct {
		name        string
		before      string
		want        string
		wantChanged bool
	}{
		{
			name:        "lua clamshell rules",
			before:      GeneratedLuaHeader + "\nhl.monitor({ output = \"eDP-1\", disabled = true })\n",
			want:        GeneratedLuaHeader + "\n",
			wantChanged: true,
		},
		{
			name:        "legacy clamshell rules",
			before:      GeneratedLegacyHeader + "\nmonitor = eDP-1, disable\n",
			want:        GeneratedLegacyHeader + "\n",
			wantChanged: true,
		},
		{
			name:   "already neutral",
			before: GeneratedLuaHeader + "\n",
			want:   GeneratedLuaHeader + "\n",
		},
		{
			name:   "user owned",
			before: "-- my monitor rules\nhl.monitor({ output = \"eDP-1\", disabled = true })\n",
			want:   "-- my monitor rules\nhl.monitor({ output = \"eDP-1\", disabled = true })\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "monitors.lua")
			if err := os.WriteFile(path, []byte(tt.before), 0o644); err != nil {
				t.Fatalf("write fixture: %v", err)
			}
			changed, err := NeutralizeGeneratedMonitorsConfig(path)
			if err != nil {
				t.Fatalf("neutralize: %v", err)
			}
			if changed != tt.wantChanged {
				t.Fatalf("changed = %t, want %t", changed, tt.wantChanged)
			}
			got, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read result: %v", err)
			}
			if string(got) != tt.want {
				t.Fatalf("result = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestVerifySourceChainFindsNestedRelativeSource(t *testing.T) {
	root := t.TempDir()
	hypr := filepath.Join(root, "hypr")
	if err := os.MkdirAll(filepath.Join(hypr, "conf.d"), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	rootConfig := filepath.Join(hypr, "hyprland.conf")
	include := filepath.Join(hypr, "conf.d", "displays.conf")
	target := filepath.Join(hypr, "monitors.conf")

	if err := os.WriteFile(rootConfig, []byte("source = ./conf.d/displays.conf\n"), 0o644); err != nil {
		t.Fatalf("write root config: %v", err)
	}
	if err := os.WriteFile(include, []byte("source = ../monitors.conf\n"), 0o644); err != nil {
		t.Fatalf("write include: %v", err)
	}

	if err := VerifySourceChain(rootConfig, target); err != nil {
		t.Fatalf("expected nested source chain to verify, got %v", err)
	}
}

func TestVerifySourceChainSupportsGlobInclude(t *testing.T) {
	root := t.TempDir()
	hypr := filepath.Join(root, "hypr")
	if err := os.MkdirAll(filepath.Join(hypr, "conf.d"), 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}

	rootConfig := filepath.Join(hypr, "hyprland.conf")
	target := filepath.Join(hypr, "conf.d", "monitors.conf")

	if err := os.WriteFile(rootConfig, []byte("source = ./conf.d/*.conf\n"), 0o644); err != nil {
		t.Fatalf("write root config: %v", err)
	}
	if err := os.WriteFile(target, []byte("# generated elsewhere\n"), 0o644); err != nil {
		t.Fatalf("write target: %v", err)
	}

	if err := VerifySourceChain(rootConfig, target); err != nil {
		t.Fatalf("expected glob include to verify target path, got %v", err)
	}
}

func TestVerifySourceChainRejectsUnsourcedTarget(t *testing.T) {
	root := t.TempDir()
	rootConfig := filepath.Join(root, "hyprland.conf")
	target := filepath.Join(root, "monitors.conf")

	if err := os.WriteFile(rootConfig, []byte("source = ./input.conf\n"), 0o644); err != nil {
		t.Fatalf("write root config: %v", err)
	}

	err := VerifySourceChain(rootConfig, target)
	if err == nil {
		t.Fatal("expected verify to fail for unsourced target")
	}
	if !strings.Contains(err.Error(), "not sourced") {
		t.Fatalf("expected unsourced error, got %v", err)
	}
}

func TestResolveHyprlandConfigUsesLegacyBeforeLuaRelease(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	t.Setenv("HYPRLAND_CONFIG", "")
	t.Setenv("HYPRMONCFG_MONITORS_CONF", "")

	resolved, err := ResolveHyprlandConfig("0.54.0", "", "")
	if err != nil {
		t.Fatalf("resolve config: %v", err)
	}
	if resolved.Format != HyprConfigLegacy {
		t.Fatalf("expected legacy format, got %v", resolved.Format)
	}
	if filepath.Base(resolved.RootPath) != "hyprland.conf" {
		t.Fatalf("expected hyprland.conf root, got %s", resolved.RootPath)
	}
	if filepath.Base(resolved.MonitorsPath) != "hyprmoncfg-monitors.conf" {
		t.Fatalf("expected the generated target, got %s", resolved.MonitorsPath)
	}
}

func TestResolveHyprlandConfigUsesLegacyFor055WithoutLuaConfig(t *testing.T) {
	xdg := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", xdg)
	t.Setenv("HYPRLAND_CONFIG", "")
	t.Setenv("HYPRMONCFG_MONITORS_CONF", "")
	if err := os.MkdirAll(filepath.Join(xdg, "hypr"), 0o755); err != nil {
		t.Fatalf("mkdir hypr dir: %v", err)
	}

	resolved, err := ResolveHyprlandConfig("0.55.0", "", "")
	if err != nil {
		t.Fatalf("resolve config: %v", err)
	}
	if resolved.Format != HyprConfigLegacy {
		t.Fatalf("expected legacy format, got %v", resolved.Format)
	}
}

func TestResolveHyprlandConfigUsesLuaFor055WithLuaConfig(t *testing.T) {
	xdg := t.TempDir()
	t.Setenv("XDG_CONFIG_HOME", xdg)
	t.Setenv("HYPRLAND_CONFIG", "")
	t.Setenv("HYPRMONCFG_MONITORS_CONF", "")
	hypr := filepath.Join(xdg, "hypr")
	if err := os.MkdirAll(hypr, 0o755); err != nil {
		t.Fatalf("mkdir hypr dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(hypr, "hyprland.lua"), []byte("-- lua config\n"), 0o644); err != nil {
		t.Fatalf("write hyprland.lua: %v", err)
	}

	resolved, err := ResolveHyprlandConfig("0.55.0", "", "")
	if err != nil {
		t.Fatalf("resolve config: %v", err)
	}
	if resolved.Format != HyprConfigLua {
		t.Fatalf("expected lua format, got %v", resolved.Format)
	}
	if filepath.Base(resolved.RootPath) != "hyprland.lua" {
		t.Fatalf("expected hyprland.lua root, got %s", resolved.RootPath)
	}
	if filepath.Base(resolved.MonitorsPath) != "hyprmoncfg-monitors.lua" {
		t.Fatalf("expected the generated target, got %s", resolved.MonitorsPath)
	}
}

func TestResolveHyprlandConfigExplicitExtensionForcesFormat(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())

	luaRoot := filepath.Join(t.TempDir(), "hyprland.lua")
	resolved, err := ResolveHyprlandConfig("0.54.0", "", luaRoot)
	if err != nil {
		t.Fatalf("resolve lua config: %v", err)
	}
	if resolved.Format != HyprConfigLua {
		t.Fatalf("expected explicit .lua to force lua format, got %v", resolved.Format)
	}

	legacyRoot := filepath.Join(t.TempDir(), "hyprland.conf")
	resolved, err = ResolveHyprlandConfig("0.55.0", "", legacyRoot)
	if err != nil {
		t.Fatalf("resolve legacy config: %v", err)
	}
	if resolved.Format != HyprConfigLegacy {
		t.Fatalf("expected explicit .conf to force legacy format, got %v", resolved.Format)
	}
}

func TestResolveHyprlandConfigUsesEnvironmentOverride(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	environmentRoot := filepath.Join(t.TempDir(), "hyprland.lua")
	environmentTarget := filepath.Join(t.TempDir(), "monitors.lua")
	t.Setenv("HYPRLAND_CONFIG", environmentRoot)
	t.Setenv("HYPRMONCFG_MONITORS_CONF", environmentTarget)

	resolved, err := ResolveHyprlandConfig("0.54.0", "", "")
	if err != nil {
		t.Fatalf("resolve config: %v", err)
	}
	if resolved.Format != HyprConfigLua {
		t.Fatalf("expected environment override to force lua format, got %v", resolved.Format)
	}
	if resolved.RootPath != environmentRoot {
		t.Fatalf("expected environment root %s, got %s", environmentRoot, resolved.RootPath)
	}
	if resolved.MonitorsPath != environmentTarget {
		t.Fatalf("expected environment target %s, got %s", environmentTarget, resolved.MonitorsPath)
	}
}

func TestResolveHyprlandConfigExplicitPathOverridesEnvironment(t *testing.T) {
	t.Setenv("XDG_CONFIG_HOME", t.TempDir())
	t.Setenv("HYPRLAND_CONFIG", filepath.Join(t.TempDir(), "hyprland.lua"))
	explicitRoot := filepath.Join(t.TempDir(), "hyprland.conf")

	resolved, err := ResolveHyprlandConfig("0.55.0", "", explicitRoot)
	if err != nil {
		t.Fatalf("resolve config: %v", err)
	}
	if resolved.Format != HyprConfigLegacy {
		t.Fatalf("expected explicit path to force legacy format, got %v", resolved.Format)
	}
	if resolved.RootPath != explicitRoot {
		t.Fatalf("expected explicit root %s, got %s", explicitRoot, resolved.RootPath)
	}
}

func TestResolveHyprlandConfigPathUsesEnvironmentOverride(t *testing.T) {
	environmentRoot := filepath.Join(t.TempDir(), "hyprland.conf")
	t.Setenv("HYPRLAND_CONFIG", environmentRoot)

	resolved, err := ResolveHyprlandConfigPath("")
	if err != nil {
		t.Fatalf("resolve config path: %v", err)
	}
	if resolved != environmentRoot {
		t.Fatalf("expected environment root %s, got %s", environmentRoot, resolved)
	}
}

func TestResolveMonitorsConfPathUsesEnvironmentOverride(t *testing.T) {
	environmentTarget := filepath.Join(t.TempDir(), "monitors.conf")
	t.Setenv("HYPRMONCFG_MONITORS_CONF", environmentTarget)

	resolved, err := ResolveMonitorsConfPath("")
	if err != nil {
		t.Fatalf("resolve monitors config path: %v", err)
	}
	if resolved != environmentTarget {
		t.Fatalf("expected environment target %s, got %s", environmentTarget, resolved)
	}
}

func TestResolveMonitorsConfPathExplicitPathOverridesEnvironment(t *testing.T) {
	t.Setenv("HYPRMONCFG_MONITORS_CONF", filepath.Join(t.TempDir(), "environment.conf"))
	explicitTarget := filepath.Join(t.TempDir(), "explicit.conf")

	resolved, err := ResolveMonitorsConfPath(explicitTarget)
	if err != nil {
		t.Fatalf("resolve monitors config path: %v", err)
	}
	if resolved != explicitTarget {
		t.Fatalf("expected explicit target %s, got %s", explicitTarget, resolved)
	}
}
